

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobs
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg2://username:password@postgres:5432/jobs
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  worker:
    build: .
    command: python worker.py
    environment:
      - DATABASE_URL=postgresql+psycopg2://username:password@postgres:5432/jobs
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - postgres

volumes:
  pgdata: